### ISSUE TITLE
Windows Line endings 

### ISSUE THREAD

**Issue by eaglestorm** [NetCoreTemplates/aurelia-spa#1]
Hi
Somewhere there is a package with windows line endings.  see, https://github.com/npm/npm/issues/12371 

When I try create a new app all i get is 
`/usr/bin/env: ‘node\r’: No such file or directory `

This is due to a package using windows line endings when committing to Git.

**Comment by mythz** [comment]
I've just tested this on Windows, OSX which installs and runs without issue. 

I did run into this [gulp issue on Ubuntu](https://github.com/olefredrik/FoundationPress/issues/1312) which is now resolved with the latest `aurelia-spa` template, although it doesn't seem related to your issue.

Can you try installing the template again to see if it resolved it:

    $ dotnet-new aurelia-spa ProjectName

If it's still an issue can you provide the exact steps to repro and also your OS Version, `node -v` and `dotnet-new -v`.

If it's to do with the `dotnet-new` installer (i.e. when installing the template), you can also install templates with our `web` dotnet tool, e.g:

    $ dotnet tool install -g web
    $ web new aurelia-spa ProjectName

**Comment by eaglestorm** [comment]
Yeah I'm using Ubuntu and still getting the same error.

But i don't think its your template, when I run dotnet-new -v I get the same error

**Comment by mythz** [comment]
I can't repro this issue, you can try re-installing the cli tooling again:

    $ npm uninstall @servicestack/cli
    $ npm install -g @servicestack/cli

Otherwise you can use the `web` .NET Core dotnet tool to install the template:

    $ dotnet tool install -g web
    $ web new aurelia-spa ProjectName
